name: TRPO_2_CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование кода репозитория на ВМ
        uses: actions/checkout@v4

      - name: Установка необходимых зависимостей
        run: sudo apt update && sudo apt install -y cmake g++

      - name: Создание файлов сборки
        run: cmake .

      - name: Сборка
        run: cmake --build .
