name: TRPO_2_CI/CD

on:
  workflow_dispatch:
  push:             # Автоматический запуск после коммита
  pull_request:     # Запуск при создании или обновлении PR
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование кода репозитория на ВМ
        uses: actions/checkout@v4

      - name: Установка необходимых зависимостей
        run: sudo apt update && sudo apt install -y cmake g++ doxygen

      - name: Создание файлов сборки
        run: cmake .

      - name: Сборка
        run: cmake --build .

      - name: Тестирование
        run: ./test

      - name: Генерация документации
        run: doxygen Doxyfile

      - name: Индентиыикация
        if: github.event_name == 'push'
        run: |
          git config --global user.email "vovapo2004@gmail.com""
          git config --global user.name "Pochepayka"
          
      - name: Коммит изменений документации
        if: github.event_name == 'push'
        run: |
          git add docs/
          git commit -m "Автоматичесткое обновление документации"
          git push 